### ISSUE TITLE
Ethernet frame padding functionality duplicated?

### ISSUE THREAD

**Issue by paul-pearce** [google/gopacket#229]
Hello,

gopacket generates ethernet frames for TCP handshakes that are 6 bytes larger (60 bytes not counting fcs) than what some other libraries and tools will generate (54 bytes not counting fcs). Examples I checked against were dpkt for generation and zmap as a tool. The code to perform this is here:

https://github.com/google/gopacket/blob/master/layers/ethernet.go#L94

As the code comment indicates this is to comply with the minimum ethernet frame size of 60 bytes (not counting fcs). But this seems to be duplicating kernel / driver / NIC hardware functionality that will automatically pad frames to the proper length as needed.

I'm not sure what the right answer here. I just wanted to flag it so you can make the decision on if you want to continue handling this in your code or defer this to the network stack as other libraries and tools appear to have done.

**Comment by lhausermann** [comment]
@gconnell any guidance here ?

**Comment by gconnell** [comment]
I'm not 100% sure, but I think I put that code in because otherwise at least one program I tried to write failed.  It may be that AF_PACKET doesn't allow <60byte, but pcap does, or PF_RING does but pcap doesn't, or something like that.  Or it could be entirely superfluous code that just takes up space and increases my KLOC github stats ;)

Unless there's an actual bug causing this to fail, I'd lean towards keeping things as they are.

**Comment by paul-pearce** [comment]
I originally raised the issue as it posed some sort of analysis challenge. Unfortunately, it's been so long I no longer remember the specific context.

I'm fairly certain that AF_PACKET and pcap both are fine with < 60 byte packets. I can't speak to PF_RING (although that would not surprise me given the context).

How about you go ahead and close it and if I re-encounter the analysis issue I'll re-open and comment.

**Comment by lhausermann** [comment]
Ok. Let's close it for now.
