### ISSUE TITLE
reassembly for tcp long connection

### ISSUE THREAD

**Issue by orange-jacky** [google/gopacket#257]
Package tcpassembly  can reassemble tcp short connection, and can't reassembly tcp long connection.
      I would like to know how to reassemble the long tcp connection?
      Anyone can give me a method or a demo? thanks

**Comment by gconnell** [comment]
Not sure what you mean by "tcp long connections", could you provide details on what you mean here?

tcpassembly should be able to reassemble a stream regardless of the time the connection is open.

**Comment by orange-jacky** [comment]
- 

- [ ] 

- [ ]

**Comment by orange-jacky** [comment]
@gconnell  tcpassembly can able to reassemble a stream with tcp.flags of syn,ack,rst,fin, and sometimes  a stream  only has tcp.flags of psh&ack, ack. I plan to reassemble this stream, how to do it? thank you

**Comment by orange-jacky** [comment]
@gconnell tcpassembly can able to reassemble a stream with tcp.flags of syn,ack,rst,fin, and sometimes a stream only has tcp.flags of psh&ack, ack. I plan to reassemble this stream, how to do it? thank you

**Comment by gconnell** [comment]
Ah, you're interested in assembling a stream that you didn't see start, that makes sense!

If tcpassembly doesn't see an initial SYN, it assumes the SYN may have been dropped/reordered and waits for it to appear.  If you start watching a TCP stream after the SYN goes through, though, this will never happen.  Setting MaxBufferedPagesPerConnection or MaxBufferedPagesTotal should fix this for you... I'd start by setting MaxBufferedPagesPerConnection to something like 16... this means that if it sees 16 new packets for a single connection, it'll force pushing data through regardless of a drop.  Note that when it pushes data in this way (with known missing data), Reassembly.Skip will be nonzero.

We should probably more intelligently handle this, since if we see data for a connection, we can assume the handshake has probably finished.

**Comment by lhausermann** [comment]
We are working on this to update our patch.. sorry for the long delay but should be available soon, as we really want a sustainable gopacket community

**Comment by orange-jacky** [comment]
@gconnell @lhausermann  thanks for your replies.
There is a problem that needs to be explained. Sometime the payload of one psh,ack traffic packet  represents a complete data protocol, and sometime else, the payloads of more than one psh,ack traffic packets  represent a complete data protocol, and the packets number is random. maybe 16,also others.

I have post some pcap files,please check it.
I am looking forward to reply.
Best wishes.

[sample3.pcap.zip](https://github.com/google/gopacket/files/620725/sample3.pcap.zip)
[sample.pcap.zip](https://github.com/google/gopacket/files/620721/sample.pcap.zip)
[sample2.pcap.zip](https://github.com/google/gopacket/files/620724/sample2.pcap.zip)

**Comment by gconnell** [comment]
In TCP, data is split arbitrarily between packets, so there's no guarantee that a single packet will contain a complete message, for whatever definition of a "message" is used by the application protocol.  In other words, TCP is a "stream" protocol, meaning that it simply pushes a continuous stream of packets from A to B, with no message splits in the stream. https://en.wikipedia.org/wiki/Transmission_Control_Protocol contains lots of information on how TCP works in general, specifically the "Protocol Operation" section.

Closing this for now, but if you have any other questions related to how gopacket handles TCP, feel free to reopen and ask them.

**Comment by orange-jacky** [comment]
@gconnell  thanks
