### ISSUE TITLE
Why is gopacket modifying packets?

### ISSUE THREAD

**Issue by floren** [google/gopacket#379]
We have an application which analyzes packets from read-only memory-mapped files. We found that the code segfaults in `github.com/google/gopacket/layers.(*RadioTap).DecodeFromBytes` (`github.com/google/gopacket/layers/radiotap.go:867`). Digging a bit, we found that #73 introduces code there which appears to *modify the packet*. This seems problematic for analyzing packets; if a packet appears without a checksum, we'd rather know that it didn't have a checksum than have gopacket silently gin one up on our behalf.

**Comment by gconnell** [comment]
Yep, that's weird and unexpected... definitely a bug to be fixed.  I'll have to dig a bit to figure out exactly why it's happening (it's in the radiotap.go change, lines 410-416 in that PR).  If you have any experience with the layer types in question and would like to submit a fix, I'd happily accept it :)

**Comment by floren** [comment]
We hacked out that stuff around lines 410-416 and it seems to be working for our needs, but the code doesn't pass 'go test' after that change; fixing that may involve a knowledge of gopacket's inner workings that surpasses our (extremely limited) understanding.

**Comment by traetox** [comment]
I dug into this trying to understand what is happening and fix it, but there are two things that are kind of killing us.

1. Because the code in radiotap.go:867 uses an append, if the slice handed in has extra capacity (Cap > Len) then it writes in place.  If the slice being handed in is a subslice of a larger data structure (e.g. we are walking packets that we got via some optimized decoder or file backed memory map) then the cap will be greater than the len and the append will either destroy the data around the packet or write to RO memory.
2.  The radiotap has no way to pass the fact that there was no FCS to any subsequent layers.  So even if we wanted to intelligently choose to populate the Checksum in the Dot11 structure, we have no way to know if that should be done.

There are a few options going forward here:
1.  All packets have a (*reflect.SliceHeader)(unsafe.Pointer(&data)).Cap = len(data) at the start of processing.  Not sure how much of a performance hit this causes, and the purists will likely freak out and doesn't solve the issue where the checksum is just whipped up.
2.  There needs to be some information passing from Radiotap to Dot11 telling it whether the FCS was present, or Dot11 does not assume that the Checksum is there and chop it off the Payload (maybe the FCS is treated as an additional layer).

I REALLY don't like the idea of just tacking on a valid Checksum if its not there, but the architecture as is doesn't support intelligently passing its existence to Dot11.  I wanted to bounce this around a bit before I build out a PR that won't get pulled or doesn't make sense.  Thoughts?

**Comment by traetox** [comment]
The other hacky option is to just pull the checksum in the dot11 parser as the last 4 bytes (as it does now) regardless of whether its there or not, but don't chop it off the payload.  If it's there, great, if it's not then the checksum is bad.  This shouldn't effect any downstream parser and no major changes are required.

**Comment by mspielberg** [comment]
> If the slice being handed in is a subslice of a larger data structure (e.g. we are walking packets that we got via some optimized decoder or file backed memory map) then the cap will be greater than the len and the append will either destroy the data around the packet or write to RO memory.

When creating your subslices of a larger structure (i.e. mapped memory page), you can and should set the cap() of your subslice using the 3-argument slicing syntax (See "Full slice expressions" at https://golang.org/ref/spec#Slice_expressions). No hackery with unsafe.Pointer necessary, and it keeps your larger structure safe from append().

**Comment by traetox** [comment]
agreed (which is what our current work around is), but the parser is still just injecting valid checksums (even when there aren't any) and it requires the user to know that they have to protect their slices via reflection when using the library (which seems like a bad idea).  I am going to submit a PR that removes the checksum injection.

**Comment by notti** [comment]
This was addressed by #395
