### ISSUE TITLE
What does the gopacket to do with  fragmented IPv4 datagram?

### ISSUE THREAD

**Issue by lcplj123** [google/gopacket#406]
I have read the gopacket source code, and found that if a packet is fragmented, the packet's TCPLayer is nil, it seems that the fragmented packet is ignored! 
Who can explain？

**Comment by gconnell** [comment]
Not quite.  The TCP layer is nil because there's no TCP layer on the packet :)

GoPacket's initial parsing is single-packet with no shared state, so it parses the best it can.  Generally, the first packet in a fragment set will have a full TCP header, so GoPacket will happily parse it.  Subsequent packets, though, will not, so it'll generally have a stack that's something like (Ethernet/IPv4/Fragment).  Each packet is parsed individually, so that's the best it can do.

If you do want IPv4 defrag, you can use the (stateful) gopacket/ip4defrag library to keep track of past fragments and put together fragments once the entire packet is available.

**Comment by lcplj123** [comment]
Well, thanks。
If i use assembler.AssembleWithTimestamp, will it goes wrong cause the function only accepts packets with TransportLayer, those without transportlayer will be dropped.
