### ISSUE TITLE
Mistake in LLDP ChassisID types constants

### ISSUE THREAD

**Issue by baba147** [google/gopacket#450]
`LLDPChassisIDSubtypeIfaceName   LLDPChassisIDSubType = 6`

should be:

`LLDPChassisIDSubTypeIfaceName   LLDPChassisIDSubType = 6`

Notice the capitalization of "T" in SubType.

**Comment by gconnell** [comment]
Thanks for submitting a patch!  Really appreciate the contribution, and I hope to see more from you in the future!

That said, I'm going to push back against this, I'm afraid.  While I definitely see your point here, the issue is that this change is backwards incompatible and could break folks that reference LLDPChassisIDSubtypeIfaceName in their existing code.  And while there's definitely an argument for SubType, there's one for Subtype as well (since it's a single, full word: http://www.dictionary.com/browse/subtype).  Were it grossly misspelled, I think there'd be sufficient reason for a breaking change.  Given that this appears to be a 50/50, I'll lean away from breaking code.

Should you feel strongly, feel free to push back with your arguments and I'll be happy to review them.  Thanks again for contributing!

**Comment by baba147** [comment]
My apologies. I should have been more clear. The issue is not the capitalization itself. The issue is that the case on that particular line is different from all surrounding lines:

    const (
	LLDPChassisIDSubTypeReserved    LLDPChassisIDSubType = 0
	LLDPChassisIDSubTypeChassisComp LLDPChassisIDSubType = 1
	LLDPChassisIDSubtypeIfaceAlias  LLDPChassisIDSubType = 2
	LLDPChassisIDSubTypePortComp    LLDPChassisIDSubType = 3
	LLDPChassisIDSubTypeMACAddr     LLDPChassisIDSubType = 4
	LLDPChassisIDSubTypeNetworkAddr LLDPChassisIDSubType = 5
	LLDPChassisIDSubtypeIfaceName   LLDPChassisIDSubType = 6
	LLDPChassisIDSubTypeLocal       LLDPChassisIDSubType = 7
)

It should be consistent.
