### ISSUE TITLE
Build fails when using 'pfring 7.2.0-stable'

### ISSUE THREAD

**Issue by derktam** [google/gopacket#467]
**vendor/github.com/google/gopacket/pfring/pfring.go:155: r.pkthdr.extended_hdr.if_index undefined (type C.struct_pfring_extended_pkthdr has no field or method if_index)**

   

- PF_RING/kernel/linux/pf_ring.h  (branch 7.2.0-stable)
```
struct pfring_extended_pkthdr {
  u_int64_t timestamp_ns;  /* Packet timestamp at ns precision. Note that if your NIC supports
                  hardware timestamp, this is the place to read timestamp from */
#define PKT_FLAGS_CHECKSUM_OFFLOAD    1 << 0 /* IP/TCP checksum offload enabled */
#define PKT_FLAGS_CHECKSUM_OK         1 << 1 /* Valid checksum (with IP/TCP checksum offload enabled) */
#define PKT_FLAGS_IP_MORE_FRAG        1 << 2 /* IP More fragments flag set */
#define PKT_FLAGS_IP_FRAG_OFFSET      1 << 3 /* IP fragment offset set (not 0) */
#define PKT_FLAGS_VLAN_HWACCEL        1 << 4 /* VLAN stripped by hw */
#define PKT_FLAGS_FLOW_OFFLOAD_UPDATE 1 << 6 /* Flow update metadata, see generic_flow_update struct (keep flag compatible with ZC) */
#define PKT_FLAGS_FLOW_OFFLOAD_PACKET 1 << 7 /* Flow raw packet, pkt_hash contains the flow_id (keep flag compatible with ZC) */
#define PKT_FLAGS_FLOW_OFFLOAD_MARKER 1 << 8 /* Flow raw packet belongs to a flow that has been marked (keep flag compatible with ZC) */
  u_int32_t flags;

  u_int8_t rx_direction;   /* 1=RX: packet received by the NIC, 0=TX: packet transmitted by the NIC */
  int32_t  if_index;       /* index of the interface on which the packet has been received.
                  It can be also used to report other information */
  u_int32_t pkt_hash;      /* Hash based on the packet header */

  /* --- short header ends here --- */

  struct {
    int32_t bounce_interface; /* Interface Id where this packet will bounce after processing
                 if its values is other than UNKNOWN_INTERFACE */
    struct sk_buff *reserved; /* Kernel only pointer */
  } tx;

  /* NOTE: leave it as last field of the memset on parse_pkt() will fail */
  struct pkt_parsing_info parsed_pkt; /* packet parsing info */
} __attribute__((packed));

/* NOTE: Keep 'struct pfring_pkthdr' in sync with 'struct pcap_pkthdr' */

struct pfring_pkthdr {
  /* pcap header */
  struct timeval ts;    /* time stamp */
  u_int32_t caplen;     /* length of portion present */
  u_int32_t len;        /* length of whole packet (off wire) */
  struct pfring_extended_pkthdr extended_hdr; /* PF_RING extended header */
} __attribute__((packed));

```

The structure seems to have not changed from the previous version, but a build error occurs.

**Comment by solidgoldbomb** [comment]
I ran into the same issue recently.  The root cause was not immediately obvious to me because it seemed to work on *some* machines even though they had PF_RING 7.2.0 installed.  The machines that *seemed* to be working only did so because they happened to have cached build artifacts which were built previously when I had an older 7.0.0 PF_RING.

This issue is readily reproduced by running the build against PF_RING 7.2.0 and forcing it to not use any cached build artifacts.

This is caused by a change in the alignment within ```struct pfring_extended_pkthdr``` between PF_RING v7.0.0 and v7.2.0.  In 7.2.0, some of the fields became unaligned due to the addition of the ```__attribute__((packed))``` in all of the structs in pfring.h.

The cgo tools don't allow access from golang to any unaligned/misaligned fields within a C structure.  To enforce this, cgo hides all of the unaligned fields deliberately.  See: https://golang.org/cmd/cgo/#hdr-Go_references_to_C

> Within the Go file, C's struct field names that are keywords in Go can be accessed by prefixing them with an underscore: if x points at a C struct with a field named "type", x._type accesses the field. C struct fields that cannot be expressed in Go, **such as bit fields or misaligned data, are omitted in the Go struct**, replaced by appropriate padding to reach the next field or the end of the struct. 

In PF_RING 7.0.0, fields are **not packed** so they are properly aligned by the C compiler:
https://github.com/ntop/PF_RING/blob/7.0.0-stable/kernel/linux/pf_ring.h#L302

In PF_RING 7.2.0, fields **are packed** so they are allowed to be unaligned by the C compiler:
https://github.com/ntop/PF_RING/blob/7.2.0-stable/kernel/linux/pf_ring.h#L306

The cgo output when building against PF_RING 7.2.0 looks like this.  Note the (1-byte) ```u_int8_t rx_direction``` just before the ```if_index``` field that is causing the issue for all fields after that one.  Basically, golang code can't see/access the ```if_index``` field and this is an intentional action by cgo.
```
type _Ctype_struct_pfring_extended_pkthdr struct {
        timestamp_ns    _Ctype_u_int64_t
        flags           _Ctype_u_int32_t
        rx_direction    _Ctype_u_int8_t
        _               [4]byte
        _               [4]byte
        _               [16]byte
        _               [127]byte
}

type _Ctype_struct_pfring_pkthdr struct {
        ts              _Ctype_struct_timeval
        caplen          _Ctype_u_int32_t
        len             _Ctype_u_int32_t
        extended_hdr    _Ctype_struct_pfring_extended_pkthdr
}
```
For my use case, I wasn't actually using the extended packet header fields so I worked around the issue by hacking out the reference to if_index and rebuilding.
