### ISSUE TITLE
Disassociation Vendor-specific Elements not parsed?

### ISSUE THREAD

**Issue by Galadros** [google/gopacket#596]
So I'm doing some other code writing, and I came across something that I don't understand.

```
func (m *Dot11MgmtDeauthentication) DecodeFromBytes(data []byte, df gopacket.DecodeFeedback) error {
	if len(data) < 2 {
		df.SetTruncated()
		return fmt.Errorf("Dot11MgmtDeauthentication length %v too short, %v required", len(data), 2)
	}
	m.Reason = Dot11Reason(binary.LittleEndian.Uint16(data[0:2]))
	m.Payload = data[2:]
	return m.Dot11Mgmt.DecodeFromBytes(data, df)
}
```

The above is the function that decodes Deauth frame bodies, and it mostly makes sense to me.  However, I found the following in the 2016 802.11 spec, in 9.3.3.14

**Table 9-37—Deauthentication frame body:**

Order | Information
------- | --------------
1   |  Reason code
Last – 1 | One or more vendor-specific elements are optionally present.
Last | The Management MIC element (MME) is present when management frame
protection is enabled at the AP and the frame is a group addressed frame.

I'm confused at why `gopacket` doesn't account at all for the possible vendor-specific elements (at least that I can see).  Am I missing something?  Or does gopacket simply fail to parse any Deauth frame that includes those elements?  I'd appreciate some feedback!

**Comment by notti** [comment]
`Reason code` is part of "Fields that are not elements" (9.4.1), while `vendor-specific` and `MME` are part of "Elements" (9.4.2) = `Dot11InformationElement` (ids already defined as `Dot11InformationElementIDVendor` and `Dot11InformationElementIDManagementMIC`)
The rest of the code decodes this `Dot11InformationElement`s by returning them as next layer (the same as you did in your pull request) -> you don't need to account for those.
Only 9.4.1 elements must be decoded in `DecodeFromBytes`, while 9.4.2 elements are handled by the nex tlayer `Dot11InformaionElement`


Offtopic:
IMHO it would have been better to decode all the elements in `DecodeFromBytes` and put the 9.4.2 elements into a slice (and not implement layer in `Dot11InformationElement`), but that ship has sailed, since it was already implemented this way.

**Comment by Galadros** [comment]
@notti just re: your offtopic comment?  Yeah I bloody well agree... I was kind of baffled when I saw that information elements were separated into a different layer.

**Comment by notti** [comment]
Yeah, I'm not sure if we can fix that somehow....
Maybe do both for the existing ones (add them as a list to the message type, and return it as nextlayer), add them as a list to the newly implemented ones, and mark using them as layertype as obsolete in the documentation?
