### ISSUE TITLE
undefined: strings.Builder

### ISSUE THREAD

**Issue by rakeshlacework** [google/gopacket#631]
in # github.com/google/gopacket/layers
../../google/gopacket/layers/dns.go:820:11: undefined: strings.Builder

strings.Builder is not available in golang 1.9

**Comment by somnusx** [comment]
This is a version issue, the go language version is greater than go 1.10，Please use the latest version of go1.12.2

**Comment by somnusx** [comment]
> in # github.com/google/gopacket/layers
> ../../google/gopacket/layers/dns.go:820:11: undefined: strings.Builder
> 
> strings.Builder is not available in golang 1.9

This is a version issue, the go language version is greater than go 1.10，Please use the latest version of go1.12.2

**Comment by rakeshlacework** [comment]
imho enforcing toolchain version should be really considered carefully. there are alternates like bytes.Buffer which can be used (agreed not the most optimal solution however it does not break dependencies)

**Comment by rakeshlacework** [comment]
btw build tags were added as part of golang 1.9+ for that very reason

**Comment by notti** [comment]
> > in # github.com/google/gopacket/layers
> > ../../google/gopacket/layers/dns.go:820:11: undefined: strings.Builder
> > strings.Builder is not available in golang 1.9
> 
> This is a version issue, the go language version is greater than go 1.10，Please use the latest version of go1.12.2

That's actually a gopacket issue, since we state in https://github.com/google/gopacket/blob/7f3fc6cbbb499248dca53da7fe3ed6c25a78d22f/README.md and https://github.com/google/gopacket/blob/7f3fc6cbbb499248dca53da7fe3ed6c25a78d22f/doc.go that we require go >= 1.5. This was an oversight during code review (I already had the plan to improve ci, but still haven't found time yet).
Should be fixed now.

Funny sidenote: The code in question wasn't actually working, since CLASS has a different meaning in OPT...
